config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
  	resources :reviews
  end
  resources :favorite_books
  get '/favorites', to: 'favorite_books#index', as: 'favorites'
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  belongs_to :genre
  has_many :reviews
  has_many :favorite_books # just the 'relationships'
  has_many :favorited_by, through: :favorite_books, source: :user

  has_attached_file :book_img, :styles => { :book_index => "250x350>", :book_show => "325x475>" }
  validates_attachment_content_type :book_img, :content_type => /\Aimage\/.*\Z/
end

  

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/favorite_book.rb
class FavoriteBook < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books
  has_many :reviews
  has_many :favorites
  has_many :favorite_books, through: :favorites, source: :favorited, source_type: 'Book'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :find_book, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def index
	  if params[:genre].blank?
	    @books = Book.all
	  else
	  	@genre_id = Genre.find_by(name: params[:genre]).id
	  	@books = Book.where(:genre_id => @genre_id)
	  end
	end

	def show
	end

	def new
	  @book = current_user.books.build
	  @genres = Genre.all.map{ |g| [g.name, g.id] }
	end

	def create
	  @book = current_user.books.build(book_params)
	  @book.category_id = params[:category_id]
	  
	  if @book.save
	  	redirect_to root_path
	  else
	  	render 'new'
	  end
	end

	def edit
	  @genres = Genre.all.map{ |g| [g.name, g.id] }
	end

	def favorite
    type = params[:type]
    if type == "favorite"
      current_user.favorites << @book
      redirect_to :back, notice: 'You favorited #{@book.name}'

    elsif type == "unfavorite"
      current_user.favorites.delete(@book)
      redirect_to :back, notice: 'Unfavorited #{@book.name}'

    else
      # Type missing, nothing happens
      redirect_to :back, notice: 'Nothing happened.'
    end
  end

	def update
	  @book.genre_id = params[:genre_id]
	  if @book.update(book_params)
		redirect_to book_path(@book)
	  else
		render 'edit'
	  end
	end

	# def destroy
	#   @book.destroy
	#   redirect_to root_path
	# end

	private

	  def book_params
	  	params.require(:book).permit(:title, :synopsis, :author, :genre_id, :book_img)
	  end

	  def find_book
	  	@book = Book.find(params[:id])
	  end

end

app/controllers/favorite_books_controller.rb
class FavoritebooksController < ApplicationController
  before_action :set_book
  
  def create
    if Favorite.create(favorited: @book, user: current_user)
      redirect_to @book, notice: 'book has been favorited'
    else
      redirect_to @book, alert: 'Something went wrong...*sad panda*'
    end
  end
  
  def destroy
    Favorite.where(favorited_id: @book.id, user_id: current_user.id).first.destroy
    redirect_to @book, notice: 'book is no longer in favorites'
  end
  
  private
  
  def set_book
    @book = book.find(params[:book_id] || params[:id])
  end
end

app/controllers/favorites_controller.rb
class FavoriteBooksController < ApplicationController
  before_action :set_book

  def index
    @favorites = current_user.favorite_books
  end

  def create
    if Favorite.create(favorited: @book, user: current_user)
      redirect_to @book, notice: 'book has been favorited'
    else
      redirect_to @book, alert: 'Something went wrong...*sad panda*'
    end
  end
  
  def destroy
    Favorite.where(favorited_id: @book.id, user_id: current_user.id).first.destroy
    redirect_to @book, notice: 'book is no longer in favorites'
  end
  
  private
  
  def set_book
    @book = book.find(params[:book_id] || params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_book
  before_action :find_review, only: [:edit, :update, :destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.book_id = @book.id
    @review.user_id = current_user.id
    if @review.save
      redirect_to book_path(@book)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  	if @review.update(review_params)
  	  redirect_to book_path(@book)
  	else
      render 'edit'
    end 
  end

  def destroy
    @review.destroy
    redirect_to book_path(@book)
  end

  private

  	def review_params
  	  params.require(:review).permit(:rating, :review)
  	end

  	def find_book
      @book = Book.find(params[:book_id])
  	end

  	def find_review
      @review = Review.find(params[:id])
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
  <%= select_tag(:genre_id, options_for_select(@genres), :prompt => "Select a genre") %>
  <%= f.file_field :book_img %>
  <%= f.input :title, label: "Book Title" %>
  <%= f.input :author %>
  <%= f.input :synopsis %>
  <%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">
<div class="row">
  <div class="col-md-10">
    <h1>Edit Book</h1>
  </div>
  <div class="col-md-2">
    <%= link_to "Go back!", book_path(@book)%>
  </div>
</div>

<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
  <%= f.select :genre_id, @genres %>
  <%= f.file_field :book_img %>
  <%= f.input :title, label: "Book Title" %>
  <%= f.input :author %>
  <%= f.input :synopsis %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/books/index.html.erb
<h1 class="current-genre"><%= params[:genre] %> Books</h1>

<div class="row">
  <% @books.each do |book| %>
   <div class="col-sm-3">
    <a href="/books/<%= book.id %>">
  	  <%= image_tag book.book_img.url(:book_index), class: "book" %>
    </a>
   </div>
  <% end %>
</div>

app/views/books/new.html.erb
<div class="col-md-6 col-md-offset-3">
<h1>New Book</h1>

<%= render 'form' %>
</div>

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-10">
    <h2><%= @book.title %></h2>
  </div>
  <div>
    <%= link_to "Back", root_path%>
    <% if user_signed_in? %>
      <%= link_to "Edit", edit_book_path(@book)%>
      <%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Didnt like this book?" }%>
      <%- unless current_user.favorite_books.exists?(id: @book.id) -%>
<%= link_to 'Add to favorites', favorite_books_path(book_id: @book), method: :post %>
<%- else -%>
<%= link_to 'Remove from favorites', favorite_book_path(@book), method: :delete %>
<%- end -%>
    <% end %> 
  </div>  
</div>

<div class="row">
  <div class="col-md-4">
    <%= image_tag @book.book_img.url(:book_show), class: "book-show" %>
  </div>
  <div class="col-md-8">
    <div class="book-info">
      <h2><%= @book.title %></h2>
      <h3>From <%= @book.author %></h3>
      <h4>Genre: <%= @book.genre.name %></h4>
      <h5>Synopsis:</h5>
      <p><%= @book.synopsis %></p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="reviews">
      <% if @book.reviews.count == 0 %>
        <h1>There are no reviews currently for this book</h1>
      <% else %>
        <h1>Reviews</h1>
        <%= render @book.reviews %>
      <% end %>
      <div>
        <%= link_to "Add Review", new_book_review_path(@book)%>
      </div>
    </div>  
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ubrary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<nav class="navbar navbar-default">
	  <div class="container">
	  	<div class="navbar-header">
	  		<%= link_to "Ubrary", root_path, class: "navbar-brand" %>
	  	</div>
	  	<ul class="nav navbar-nav  navbar-right">
	  		<li><%= link_to "Sign Up for Ubrary", new_user_registration_path %></li>
	  		<% if user_signed_in? %>
	  			<li><%= link_to favorite_books_path(@book), method: :delete do %> </li>
	  			<% end %>
	  		  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
	  		<% else %>
	  		  <li><%= link_to "Ubrary Log In", new_user_session_path %></li>
	  		<% end %>
	  	</ul>
	  	<ul class="nav navbar-nav">
	  	  <li class="dropdown">
	  	  	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Genres</a>
			<ul class="dropdown-menu" role="menu">
			  <% Genre.all.each do |genre| %>
			  	<li>
			  	  <%= link_to genre.name, books_path(genre: genre.name), class: "link" %>
			  	</li>
			  <% end %>
			</ul>
	  	  </li>
	  	  <% if user_signed_in? %>
	  	    <li><%= link_to "Add Book", new_book_path %></li>
	  	  <% end %>
	  	</ul>
	  </div>
	</nav>


    <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
	</div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@book, @book.reviews.build]) do |f| %>
  <%= f.input :rating %>
  <%= f.input :review %>
  <%= f.button :submit %>
<% end %>

app/views/reviews/_review.html.erb
<p><%= review.rating %></p>
<p><%= review.review %></p>

  <% if user_signed_in? %>

  <%= link_to "Edit", edit_book_review_path(review.book, review) %>
  <%= link_to "Delete", book_review_path(review.book, review), method: :delete, data: { confirm: "Didnt like this review?" } %>

<% end %>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">
<h1>Edit Review</h1>

<%= simple_form_for([@book, @review]) do |f| %>
  <%= f.input :rating %>
  <%= f.input :review %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">
<h1>New Review</h1>
<%= render 'form' %>
</div>